### ISSUE TITLE
signature.count not found

### ISSUE THREAD

**Issue by yoni** [yoni/r_we_the_people#2]
Received a 'signature.count' not found:

```
> jpeg() 
> plot_issues_over_time(petitions) 
Error in eval(expr, envir, enclos) : object 'signature.count' not found 
> dev.off() 
```

**Comment by yoni** [comment]
@gregelin I fixed the signature.count issue. It was caused by a change to the API where they switched from snake-case to camel-case. The fix should be in the next release of the package (i.e. 0.5) over the next day or so.

Thanks for the bug report!

**Comment by gregelin** [comment]
Thanks!
